language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: P2efW5woP00T54L+vIIcTD08px9ZtoTequ09y3155AQZm0+JpJJR6Gi445qu/fWrPd/opjTyD7inYegmzIPjvRldK1RILOEddFzk7iBL/RJjp2I7JtDRuyQ8AJJyIlcScHlSKwGr9fC9FKfiGwKfAofmxL1GmpBASABgz5c4Kl2iLcF/BudQMDP3dwg4Ys3Vt5/oWWGAxMRgssWiIQZikwdwbdllcJvhv3ETuIhAKbLYOtf8AajmlYd1M5uZxr4gi6oNA5m2gPcXUvnjjPjU19/YEPpEhCaQbKhbuohDDUzaDIPs3HZbHDHxK8bH7Nwjc97dWGRiAGXKj1v8MZ/PHkH5D0SHI5RGJx9UhBiyTrbpy14VQ6T/pCkiruxyH7FQop0k122ogPYA28KPsWl9rfTqxP5LDv5lP387isrvrzgLMoPZVTKoPeQJcEX7k5PsT0PaYpxNs/dhR9VxnGO8vY7As0p214mHiRHC09WxRASdPn3n9rXrUKgshHInUuTfqcZpeHfgq4KdtA6ke80bSTCm1VXHy2tljTTHmcG+ifpvjFt5fIgUj7grT1PuxqHWPdGQJiaiTBYsGlsjdy2gj3SsIOZngqWiUvH/fCya6FJveIMP3cQp/r3Bm6d+TWgFP1L1TkBD9yhRcZUrpkkZDan8fo0ykfbye3Sceed4Z/A=
  app: rocky-woodland-54122
  on:
    repo: ASiede/tourneytool-api
